version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  adminer:
    image: adminer
    ports:
      - "15433:8080"  # Expose Adminer on port 15433
    env_file:
      - .env
    depends_on:
      - database
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge